//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidToolkit.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AndroidToolkitDB : DbContext
    {
        public AndroidToolkitDB()
            : base("name=DefaultConnection")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Recovery> Recoveries { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<BugReport> BugReports { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
    }
}
