//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidToolkit.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recovery
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public int DeviceId { get; set; }
        public string Download { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
